name: Respond to downstream test runs as part of downstream testing


on:
  repository_dispatch:
    # To add more test responses from volttron modular repos,
    # put the name of the event type in the list below.
    # The name of the event type should come from Workflow
    # that is triggering this workflow.
    # For example, 'VOLTTRON/volttron-listener-agent` repo has a workflow
    # called downstream-testing-dispatch.yml that will send a repository
    # dispatch to this repo using with an event type called "listener-downstream-testing-response"
    types: [listener-downstream-testing-response]

jobs:
  test-response:
    runs-on: ubuntu-20.04

    steps:
      - name: Repository Dispatch Triggered
        run: |
          echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event." 
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Payload from downstream workflow: '${{ toJson(github.event.client_payload) }}'"